### PR TITLE
A few improvements

### PR DESCRIPTION
**Pull request by tommz9**
Hi,

first, I would like to thank you for the code. I used it to test one of my prototypes. However, I found a few problems while using the library:

- Missing include guard in the header file
- the code does not use SPI Transactions
- WaitForData functions are not working (it needs a while loop, not only the if statement). Right now it just returns if the measurement is not ready.
- There is a lot of repeated code in the read functions
- redefining _BV() causes a compile warning
- it is not possible to change the voltage reference source
- there are unnecessary long delays in various functions. These delays can be shorter according to the datasheet
- begin() prints out the value of the registers by default. This might interfere with the communication protocol of the application 

These are the issues that I have addressed in the code of this pull request. You can take some of it if you want.

This code has been tested on the Arduino platform for Teensy 3.2 so it might need some modifications in order to work with other Arduinos.

### CODE REVIEW

**Comment by awhitchurch** [comment]
Hello @tommz9 Thank you for the changes, looks great ! I will review the code and then merge this pull request.

Thanks again for contributing!

**Comment by SensorPlay** [comment]
@tommz9 

When I compile this I get:  Protocentral_ADS1220.cpp:25:18: fatal error: limits: No such file or directory.

I added a few generic limits.h files I found on the web, but those produced new errors.

Can you help me resolve?

**Comment by Stefanhg** [comment]
That is so awesome.. Why is this not released yet, you just saved me ALOT of time.. And i lost alot of time because of this not being released yet....... 
@tommz9 I think the SPISettings SPI_SETTINGS(2000000, MSBFIRST, SPI_MODE1);  should be named something more unique so it wouldn't interfere with other Libs using the same name for their SPI settings.

**Comment by Stefanhg** [comment]
@sensorplay if still wondering. What i did was i removed the include and at the places where he used the library i just returned 0. It works pretty well!

**Pull request merged**
